Question 3:CNN Feature Extraction With Filters and Pooling

TASK 1 : Implement Edge Detection Using Convolution

In [1]:
import cv2
import numpy as np
import matplotlib.pyplot as plt

# Load the image in grayscale
# Replace 'sample.jpg' with the correct path to your image file
image = cv2.imread('C:\Users\jyost\OneDrive\Pictures\Screenshots', cv2.IMREAD_GRAYSCALE)

# Check if the image was loaded successfully
if image is None:
    print("Error: Could not load image. Please check the file path.")
else:
    # Apply Sobel filter for edge detection in x and y directions
    sobel_x = cv2.Sobel(image, cv2.CV_64F, 1, 0, ksize=3)  # Sobel filter in X direction
    sobel_y = cv2.Sobel(image, cv2.CV_64F, 0, 1, ksize=3)  # Sobel filter in Y direction

    # Convert scale for display
    sobel_x = cv2.convertScaleAbs(sobel_x)
    sobel_y = cv2.convertScaleAbs(sobel_y)

    # Display images using Matplotlib
    plt.figure(figsize=(12, 4))

    plt.subplot(1, 3, 1)
    plt.imshow(image, cmap='gray')
    plt.title("Original Image")
    plt.axis("off")

    plt.subplot(1, 3, 2)
    plt.imshow(sobel_x, cmap='gray')
    plt.title("Sobel Edge Detection - X")
    plt.axis("off")

    plt.subplot(1, 3, 3)
    plt.imshow(sobel_y, cmap='gray')
    plt.title("Sobel Edge Detection - Y")
    plt.axis("off")

    plt.show()

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape (4266068687.py, line 7)

TASK 2 :Implement Max Pooling and Average Pooling


In [ ]:
import tensorflow as tf
import numpy as np

# Create a random 4×4 matrix as input
input_matrix = np.random.randint(1, 10, (1, 4, 4, 1)).astype(np.float32)  # Shape (batch, height, width, channels) # Changed to np.float32

# Define Max Pooling and Average Pooling layers
max_pooling = tf.keras.layers.MaxPooling2D(pool_size=(2, 2), strides=2, padding='valid')
avg_pooling = tf.keras.layers.AveragePooling2D(pool_size=(2, 2), strides=2, padding='valid')

# Apply pooling operations
max_pooled_matrix = max_pooling(input_matrix).numpy().squeeze()  # Remove unnecessary dimensions
avg_pooled_matrix = avg_pooling(input_matrix).numpy().squeeze()

# Print matrices
print("Original Matrix:\n", input_matrix.squeeze())  # Remove batch & channel dimensions for readability
print("\nMax Pooled Matrix (2×2):\n", max_pooled_matrix)
print("\nAverage Pooled Matrix (2×2):\n", avg_pooled_matrix)

Original Matrix:
 [[5. 8. 6. 2.]
 [6. 7. 9. 4.]
 [5. 6. 2. 8.]
 [7. 8. 8. 9.]]

Max Pooled Matrix (2×2):
 [[8. 9.]
 [8. 9.]]

Average Pooled Matrix (2×2):
 [[6.5  5.25]
 [6.5  6.75]]
